
export enum InformMessage {
    SUCCESS_REGISTRATION = "1",
    ERROR_REGISTRATION_CONFIRM_TOKEN = "2",
    SUCCESS_SEND_MAIL_RESET_PASS = "3",
    SUCCESS_UPDATE_PASS = "4",
    ERROR_RESEND_MAIL_ACTIVE_ACCOUNT = "5",
}
